####Create Comment
POST http://localhost:3000/api/comments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjZkNGU1OTA4MWY2ZWJmYmViYjk1N2YzIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsIm5hbWUiOiJBZG1pbiIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzI1MjM0Mjg0LCJleHAiOjE3MjUyMzQ1ODR9.wavRZIAu0WoYEnni3fVf_AohacKQirxJrxofZtwHpH8
Content-Type: application/json

{
    "title": "Comentario por el Administrador",
    "text": "Primer Comentario ;D"
}
####Create Comment
POST http://localhost:3000/api/comments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjZkNGU1OTA4MWY2ZWJmYmViYjk1N2YzIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsIm5hbWUiOiJBZG1pbiIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzI1MjM0Mjg0LCJleHAiOjE3MjUyMzQ1ODR9.wavRZIAu0WoYEnni3fVf_AohacKQirxJrxofZtwHpH8
Content-Type: application/json

{
    "title": "Respuesta para el Comentario del Administrador",
    "text": "Segundo Comentario ;D",
    "parent": "66d4fc7950f9852638952c1b"
}
####Find All
GET http://localhost:3000/api/comments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjZkNGU1OTA4MWY2ZWJmYmViYjk1N2YzIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsIm5hbWUiOiJBZG1pbiIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzI1MjMyNjE1LCJleHAiOjE3MjUyMzI5MTV9.joR3uIytsmnlHIigR8dLfrJUItXj2abYXRIUr02MBYs
####Find By Id
GET http://localhost:3000/api/comments/66d4f6f7db4b5fa4bdcca36d
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjZkNGU1OTA4MWY2ZWJmYmViYjk1N2YzIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsIm5hbWUiOiJBZG1pbiIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzI1MjMzMTMxLCJleHAiOjE3MjUyMzM0MzF9.dooyGrNpZqBHAW7rDUZS8HndifxYrdqUD93m6_CrDJk
####Update
PUT http://localhost:3000/api/comments/66d4fcb350f9852638952c20
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjZkNGU1OTA4MWY2ZWJmYmViYjk1N2YzIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsIm5hbWUiOiJBZG1pbiIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzI1MjM1ODQ1LCJleHAiOjE3MjUyMzYxNDV9.FaO4WXYkE-Lyx7etcnJhTvAMVDkrXXRyDdnk_EM8CMI
Content-Type: application/json

{
    "title": "Respuesta para el Comentario del Administrador",
    "text": "Segundo Comentario Actualizado ;D"
}