####Create Common User Al parecer crashea al intentar usar un email ya existente
POST http://localhost:3000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjZkNGU1OTA4MWY2ZWJmYmViYjk1N2YzIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsIm5hbWUiOiJBZG1pbiIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzI1MjMwMTA5LCJleHAiOjE3MjUyMzA0MDl9.VuSNpA0YU0xrrCZvAZRp8br0WUAVvF4ElksQ9ptXUBQ
Content-Type: application/json

{
    "name": "User 2",
    "email": "user2@example.com",
    "password": "user123*"
}
####Login as Admin
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@example.com",
    "password": "admin123*"
}
####Login as User
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "name": "User 3",
    "email": "user3@example.com",
    "password": "user123*"
}
####Get Users
GET http://localhost:3000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjZkNGU0MWU5ODExMGQ3YWJmYzRjMmVlIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsIm5hbWUiOiJBZG1pbiIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzI1MjI4MDgwLCJleHAiOjE3MjUyMjgzODB9.94tszBBObeZObzZ0EzyfDfH9iChdC-Q0pZLxQHaSys0
####Get User by Id
GET http://localhost:3000/api/users/66d4e43afa7f3d1c8ee98de7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjZkNGU0MWU5ODExMGQ3YWJmYzRjMmVlIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsIm5hbWUiOiJBZG1pbiIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzI1MjI4MDgwLCJleHAiOjE3MjUyMjgzODB9.94tszBBObeZObzZ0EzyfDfH9iChdC-Q0pZLxQHaSys0
####Update User by Id
PUT http://localhost:3000/api/users/66d4e43afa7f3d1c8ee98de7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjZkNGU0MWU5ODExMGQ3YWJmYzRjMmVlIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsIm5hbWUiOiJBZG1pbiIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzI1MjI4MDgwLCJleHAiOjE3MjUyMjgzODB9.94tszBBObeZObzZ0EzyfDfH9iChdC-Q0pZLxQHaSys0
Content-Type: application/json

{
    "name": "User Updates",
    "email": "user3@example.com",
    "password": "user123*"
}
####Delete User by Id
DELETE http://localhost:3000/api/users/66d4e43afa7f3d1c8ee98de7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjZkNGU0MWU5ODExMGQ3YWJmYzRjMmVlIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsIm5hbWUiOiJBZG1pbiIsInJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNzI1MjI4Mzg2LCJleHAiOjE3MjUyMjg2ODZ9.YAPV8Z5ee-IjgyTgQexlOUsrkocXzZ_rNDgmlU8CABI